version: "3.9"

services:
  squamata-upload:
    build:
      context: .
      dockerfile: Dockerfile
    image: squamata-upload:latest
    container_name: squamata-upload
    ports:
      - "3005:3005"
    env_file:
      - .env
    volumes:
      - ./credentials.json:/app/credentials.json:ro
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - squamata-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  squamata-network:
    driver: bridge
